src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TeamRepository::class)
 */
class Team
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="team")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Sujet::class, mappedBy="team")
     */
    private $sujets;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="team")
     */
    private $evenements;

    /**
     * @ORM\ManyToMany(targetEntity=Jeu::class, inversedBy="teams")
     * 
     */
    private $jeu;

    public function __toString()
    {
        if(is_null($this->nom)) {
        return 'NULL';
    }
        return $this->nom;
    }

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->sujets = new ArrayCollection();
        $this->evenements = new ArrayCollection();
        $this->jeu = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setTeam($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getTeam() === $this) {
                $user->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sujet>
     */
    public function getSujets(): Collection
    {
        return $this->sujets;
    }

    public function addSujet(Sujet $sujet): self
    {
        if (!$this->sujets->contains($sujet)) {
            $this->sujets[] = $sujet;
            $sujet->setTeam($this);
        }

        return $this;
    }

    public function removeSujet(Sujet $sujet): self
    {
        if ($this->sujets->removeElement($sujet)) {
            // set the owning side to null (unless already changed)
            if ($sujet->getTeam() === $this) {
                $sujet->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setTeam($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getTeam() === $this) {
                $evenement->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, jeu>
     */
    public function getJeu(): Collection
    {
        return $this->jeu;
    }

    public function addJeu(jeu $jeu): self
    {
        if (!$this->jeu->contains($jeu)) {
            $this->jeu[] = $jeu;
        }

        return $this;
    }

    public function removeJeu(jeu $jeu): self
    {
        $this->jeu->removeElement($jeu);

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Un compte existe déja sous cette adresse mail")
 * @UniqueEntity(fields={"nom"}, message="Ce nom est déja pris")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $role_team = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ban;

    /**
     * @ORM\ManyToOne(targetEntity=Team::class, inversedBy="users")
     */
    private $team;

    /**
     * @ORM\OneToMany(targetEntity=Sujet::class, mappedBy="user")
     */
    private $sujets;

    /**
     * @ORM\ManyToMany(targetEntity=Evenement::class, inversedBy="users")
     */
    private $evenement;

    /**
     * @ORM\ManyToMany(targetEntity=Jeu::class, inversedBy="users")
     */
    private $jeu;

    /**
     * @ORM\OneToMany(targetEntity=Messages::class, mappedBy="user")
     */
    private $messages;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_verified_team = false;

    public function __toString()
    {
        return $this->nom;
    }

    public function __construct()
    {
        $this->messagePrives = new ArrayCollection();
        $this->sujets = new ArrayCollection();
        $this->evenement = new ArrayCollection();
        $this->jeu = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRoleTeam(): ?array
    {
        return $this->role_team;
    }

    public function setRoleTeam(?array $role_team): self
    {
        $this->role_team = $role_team;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getBan(): ?\DateTimeInterface
    {
        return $this->ban;
    }

    public function setBan(?\DateTimeInterface $ban): self
    {
        $this->ban = $ban;

        return $this;
    }

    public function getTeam(): ?team
    {
        return $this->team;
    }

    public function setTeam(?team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection<int, Sujet>
     */
    public function getSujets(): Collection
    {
        return $this->sujets;
    }

    public function addSujet(Sujet $sujet): self
    {
        if (!$this->sujets->contains($sujet)) {
            $this->sujets[] = $sujet;
            $sujet->setUser($this);
        }

        return $this;
    }

    public function removeSujet(Sujet $sujet): self
    {
        if ($this->sujets->removeElement($sujet)) {
            // set the owning side to null (unless already changed)
            if ($sujet->getUser() === $this) {
                $sujet->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, evenement>
     */
    public function getEvenement(): Collection
    {
        return $this->evenement;
    }

    public function addEvenement(evenement $evenement): self
    {
        if (!$this->evenement->contains($evenement)) {
            $this->evenement[] = $evenement;
        }

        return $this;
    }

    public function removeEvenement(evenement $evenement): self
    {
        $this->evenement->removeElement($evenement);

        return $this;
    }

    /**
     * @return Collection<int, jeu>
     */
    public function getJeu(): Collection
    {
        return $this->jeu;
    }

    public function addJeu(jeu $jeu): self
    {
        if (!$this->jeu->contains($jeu)) {
            $this->jeu[] = $jeu;
        }

        return $this;
    }

    public function removeJeu(jeu $jeu): self
    {
        $this->jeu->removeElement($jeu);

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setUser($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getUser() === $this) {
                $message->setUser(null);
            }
        }

        return $this;
    }

    public function getisVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsVerifiedTeam(): ?bool
    {
        return $this->is_verified_team;
    }

    public function setIsVerifiedTeam(bool $is_verified_team): self
    {
        $this->is_verified_team = $is_verified_team;

        return $this;
    }
}

templates/team/create_sujet.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/form.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
    <section class="form">

{{ form_start(form,{attr: {class: 'mb-5 flex column'}, 'action': path('app_forum_create'), 'method': 'POST'}) }}
        <h1 class="mb-5">Nouveau sujet</h1>
{{ form_label(form.titre, "Titre" ) }}
{{ form_widget(form.titre, {'attr' : { 'class': 'mb-4'} }) }}
{{ form_label(form.description, "Description" ) }}
{{ form_widget(form.description, {'attr' : { 'class': 'mb-4'} }) }}
{{ form_label(form.description, "Message" ) }}
{{ form_widget(form.contenu) }}
{{ form_widget(form.submit, { 'label': "Créer le sujet" }) }}
                {{ form_end(form) }}
                </section>
                </main>
{% endblock %}

templates/team/create_team.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
    <section class="search_page">
{{ form_start(form,{attr: {class: 'form-control'}, 'action': path('app_team_create'), 'method': 'POST'}) }}
{{ form_widget(form.nom, { 'label': 'Nom de la team' }) }}
{{ form_widget(form.description, { 'label': 'Description de la team' }) }}
{{ form_widget(form.jeu, { 'label': 'jeu' }) }}
{{ form_widget(form.submit, { 'label': 'Crée la team' }) }}
                {{ form_end(form) }}
                </section>
                </main>
{% endblock %}

templates/team/index.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/team.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">

{% if search is not defined %}
    {% if app.user.team is defined and app.user.team is not null %}
        {% if app.user.isVerifiedTeam == "1"  %}
            <section class="team">
            <div>
            <h1>{{ app.user.team.nom }}</h1>
                <h2>{{ app.user.team.description }}</h2>
                    {% for jeu in app.user.team.jeu %}
                        <p>{{ jeu.nom }}<img src="img/jeux/{{ jeu.icone }}" alt="logo {{ jeu.nom }}" height="50" width="50"/></p>
                    {% endfor %}
                {% if app.user.isVerifiedTeam == "1"  %}
                {% if app.user.roleTeam[0] == "ROLE_ADMIN" %}
                <a class="nav_link mr button" href="{{ path('app_team_edit')}}">Modifier la team</a>
                <a class="nav_link mr button" href="{{ path('app_event_create')}}">Crée un évènement</a>
                {% endif %}
                {% if app.user.roleteam != ["ROLE_ADMIN", "ROLE_FONDATEUR"] %}
                <a class="nav_link mr button-red" href="{{ path('app_team_leave')}}">Quitter la team</a>
                {% elseif app.user.roleteam == ["ROLE_ADMIN", "ROLE_FONDATEUR"] %}
                <a class="nav_link mr button-red" href="{{ path('app_team_delete')}}">Supprimer la team</a>
                {% endif %}
                {% endif %}
            </div>

            <div>
                <a class="nav_link mr button" href="{{ path('app_team_event')}}">Les evenement</a>
                <a class="nav_link mr button" href="{{ path('app_team_sujet')}}">Les discussions</a>
                <a class="nav_link mr button" href="{{ path('app_team_user')}}">Les pilotes</a>

                {% if app.user.roleTeam[0] == "ROLE_ADMIN" or app.user.roleTeam[0] == "ROLE_MODO" %}
                    <a class="nav_link mr button" href="{{ path('app_team_confirmation')}}">Les pilotes en attentes ({{ count }})</a>
                {% endif %}

            </div>
            </section>
            {% else %}
            <section class="search_page">
            <div>
            <p>Candidature en attente pour la team :</p>
            <h1>{{ app.user.team.nom }}</h1>
                <a class="nav_link mr button-red" href="{{ path('app_team_leave')}}">Annuler la candidature</a>
            </div>
            </section>
        {% endif %}
    {% endif %}
{% endif %}

<section class="team">
    {% if search is defined %}
        <h1 class="mb-5">Voici les résultats pour "{{ search }}"</h1>
        <a class="nav_link mr" href="{{ path('app_team')}}">Retour</a>
    {% endif %}

    <div class ="search_bar my-3">
        {{ render ( controller ( 'App\\Controller\\TeamController::searchBar' )) }}
    </div>

    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        {% if app.user.team is not defined or app.user.team is null %}
            <a class="nav_link button" href="{{ path('app_team_create')}}">Crée une team</a>
        {% endif %}
    {% endif %}
    <hr>
    <div>
        <ul class="grid">
            {% if teamresult is defined %}
                {% for teamresult in teamsearch %}
                    <li>{{ teamresult.nom }}</li>
                {% endfor %}
            {% endif %}

            {% for team in teams %}
                <li><a class="nav_link button" href="{{ path('app_team_id', { 'id': team.id } )}}">{{ team.nom }}</a></li>
            {% endfor %}
        </ul>
    </div>
</section>
</main>
{% endblock %}

templates/team/search.html.twig
{{ form_start(form,{attr: {class: 'form-control'}, 'action': path('app_team_search'), 'method': 'POST'}) }}
                {{ form_widget(form.search, {'attr': {'placeholder': 'Rechercher une team'}})}}
                {{ form_end(form) }}

templates/team/team_confirm_user.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/team.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
<section class="team">
<a class="nav_link mr button" href="{{ path('app_team')}}">Retour</a>
<h1 class="my-3">Liste des pilotes en attente chez {{ app.user.team.nom }}</h1>
<ul class="pilote">
{% for user in users %}
<hr>
<li class="my-2"><a class="nav_link mr white" href="{{ path('app_profile_id', { 'id': user.id }) }}">{{ user.nom }}</a><a class="nav_link mr button" href="{{ path('app_team_confirmation_id', { 'id': user.id } )}}">Accepter</a></li>
{% endfor %}
</ul>
</section>
</main>
{% endblock %}

templates/team/team_delete.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/form.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
    <section class="form">
    <h1>Voulez vous vraiment supprimer la team {{ app.user.team.nom }} ?</h1>
        {{ form_start(form,{attr: {class: ''}, 'action': path('app_team_delete'), 'method': 'POST'}) }}
        {{ form_widget(form.submit, { 'label': 'Supprimer la team' }) }}
        {{ form_end(form) }}
    </section>
</main>
{% endblock %}

templates/team/team_edit.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/form.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
    <section class="form">
        {{ form_start(form,{attr: {class: 'mb-5 flex column'}, 'action': path('app_team_edit'), 'method': 'POST'}) }}
                {{ form_label(form.nom, 'Nom de team' ) }}
                {{ form_widget(form.nom, {'attr': {'placeholder': app.user.team.nom, 'class': 'mb-4' }})}}
                {{ form_label(form.description, 'Description') }}
                {{ form_widget(form.description, {'attr': {'placeholder': app.user.team.description, 'class': 'mb-4' }})}}
                {% for checkbox in form.jeu %}
                <div>
                {{ form_label(checkbox) }}
                {{ form_widget(checkbox, {'attr' : {'class': 'mb-4'}})}}
                </div>
                {% endfor %}
        {{ form_widget(form.submit, { 'label': 'Modifier les informations de la team' }) }}
        {{ form_end(form) }}
    </section>
</main>
{% endblock %}

templates/team/team_event.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/home.css' }}">
 <link rel="stylesheet" href="{{ 'css/team.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
<section class="team">
<a class="nav_link mr button" href="{{ path('app_team')}}">Retour</a>
<h1 class="my-3">Liste des évènements chez {{ app.user.team.nom }}</h1>
<ul class="grid">
{% for event in app.user.team.evenements %}
 <li>
                    <a class="nav_link mr black" href="{{ path('app_event_id', { 'id': event.id } )}}">
                        <div class="vignette event_container">
                            <div>
                                <div class="longue_bulle detail_event marge red police_course" >{{ event.dateTime|date('d/m') }}</div>
                                <div class="longue_bulle detail_event marge red police_course" >{{ event.dateTime|date('H:i') }}</div>
                            </div>
                            <div>
                                <div class="longue_bulle marge">{{ event.nom }}</div>
                                <div class="longue_bulle marge">{{ event.team.nom }}</div>
                                <div class="longue_bulle detail_event">
                                    <div><span class="red police_course">{{ event.users|length }}/{{ event.nbPlace }}</span> participant(s)</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
{% endfor %}
</ul>
</section>
</main>
{% endblock %}

templates/team/team_page.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ '/css/home.css' }}">
 <link rel="stylesheet" href="{{ '/css/team.css' }}">
 <link rel="stylesheet" href="{{ '/css/search.css' }}">
 {% endblock %}

{% block body %}
<main class="wrapper">
<section class="team">
            <div>
            <h1>{{ team.nom }}</h1>
                <h2>{{ team.description }}</h2>
                {% for jeu in team.jeu %}
                <p>{{ jeu.nom }}<img src="/img/jeux/{{ jeu.icone }}" alt="logo {{ jeu.nom }}" height="50" width="50"/></p>
                {% endfor %}
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                    {% if app.user.team == team %}
                        {% if app.user.isVerifiedTeam == "0" %}
                            <a class="nav_link mr button" href="{{ path('app_team_leave')}}">Annuler la candidature</a>
                        {% elseif  app.user.isVerifiedTeam == "1" %}
                            {% if app.user.roleteam != ["ROLE_ADMIN", "ROLE_FONDATEUR"]%}
                            <a class="nav_link mr button" href="{{ path('app_team_leave')}}">Quitter la team</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    {% if app.user.team == null %}
                        <a class="nav_link mr button" href="{{ path('app_team_join', { 'id': team.id } )}}">Rejoindre la team</a>
                    {% endif %}
                {% endif %}
                <div class="pilote my-5">
                <h3>Liste des pilotes ({{ count }} membre(s))</h3>
                    {% for user in users %}
                        <p class="my-2"><a class="nav_link white" href="{{ path('app_profile_id', { 'id': user.id }) }}">{{ user.nom }}</a></p>
                    {% endfor %}
                </div>
                <div>
                 <h3>Liste des events</h3>
                <ul class="grid">
                    {% for event in team.evenements %}
                         <li>
                    <a class="nav_link mr black" href="{{ path('app_event_id', { 'id': event.id } )}}">
                        <div class="vignette event_container">
                            <div>
                                <div class="longue_bulle detail_event marge red police_course" >{{ event.dateTime|date('d/m') }}</div>
                                <div class="longue_bulle detail_event marge red police_course" >{{ event.dateTime|date('H:i') }}</div>
                            </div>
                            <div>
                                <div class="longue_bulle marge">{{ event.nom }}</div>
                                <div class="longue_bulle marge">{{ event.team.nom }}</div>
                                <div class="longue_bulle detail_event">
                                    <div><span class="red police_course">{{ event.users|length }}/{{ event.nbPlace }}</span> participant(s)</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                    {% endfor %}
                </ul>
                </div>
            </div>
</section>
</main>
{% endblock %}

templates/team/team_user.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
 <link rel="stylesheet" href="{{ 'css/team.css' }}">
 <link rel="stylesheet" href="{{ 'css/search.css' }}">
 {% endblock %}

{% block body %}
    <main class="wrapper">
        <section class="team">
            <a class="nav_link mr button" href="{{ path('app_team')}}">Retour</a>
            <h1 class="my-3">Liste des pilotes chez {{ app.user.team.nom }}</h1>
            <ul class="pilote">
                {% for user in users %}
                <hr>
                    <li class="my-2">
                        <a class="nav_link white" href="{{ path('app_profile_id', { 'id': user.id }) }}">{{ user.nom }}</a>
                        {% if user.roleTeam == ["ROLE_ADMIN", "ROLE_FONDATEUR"] %}
                            <span class="mr role black">- Fondateur</span>
                        {% elseif user.roleTeam == ["ROLE_ADMIN"] %}
                            <span class="mr role black">- Admin</span>
                        {% elseif user.roleTeam == ["ROLE_MODO"] %}
                            <span class="mr role black">- Modérateur</span>
                        {% else %}
                            <span class="mr role black">- Membre</span>
                        {% endif %}

                        {% if app.user.roleTeam[0] == "ROLE_ADMIN" or app.user.roleTeam[0] == "ROLE_MODO" %}

                            {% if app.user.id != user.id %}

                                {% if user.roleTeam[0] != "ROLE_ADMIN" %}

                                    {% if app.user.roleTeam == ["ROLE_ADMIN", "ROLE_FONDATEUR"] %}
                                        <a class="nav_link mr button" href="{{ path('app_promote_user', { 'id': user.id } )}}">Promouvoir le pilote</a>
                                    {% elseif app.user.roleTeam[0] == "ROLE_ADMIN" and user.roleTeam[0] == "ROLE_MEMBRE" %}
                                        <a class="nav_link mr button" href="{{ path('app_promote_user', { 'id': user.id } )}}">Promouvoir le pilote</a>
                                    {% elseif app.user.roleTeam[0] == "ROLE_MODO" and user.roleTeam[0] == "ROLE_MEMBRE" %}
                                        <a class="nav_link mr button" href="{{ path('app_promote_user', { 'id': user.id } )}}">Promouvoir le pilote</a>
                                    {% endif %}

                                {% endif %}

                                {% if user.roleTeam[0] != "ROLE_MEMBRE" %}
                                
                                    {% if app.user.roleTeam == ["ROLE_ADMIN"] and user.roleTeam[0] != "ROLE_ADMIN" %}
                                        <a class="nav_link mr button" href="{{ path('app_demote_user', { 'id': user.id } )}}">Rétrograder le pilote</a>
                                    {% elseif app.user.roleTeam == ["ROLE_ADMIN", "ROLE_FONDATEUR"]%}
                                        <a class="nav_link mr button" href="{{ path('app_demote_user', { 'id': user.id } )}}">Rétrograder le pilote</a>
                                    {% endif %}

                                {% endif %}

                                {% if user.roleTeam[0] != "ROLE_ADMIN" or app.user.roleTeam == ["ROLE_ADMIN", "ROLE_FONDATEUR"] %}
                                    <a class="nav_link mr button" href="{{ path('app_team_leave_id', { 'id': user.id } )}}">Supprimer le pilote</a>
                                {% endif %}

                                {% if app.user.roleTeam == ["ROLE_ADMIN", "ROLE_FONDATEUR"] and user.roleTeam == ["ROLE_ADMIN"] %}
                                    <a class="nav_link mr button" href="{{ path('app_transfer_propriety', { 'id': user.id } )}}">Transferer la propriété de la team</a>
                                {% endif %}

                            {% endif %}

                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </section>
    </main>
{% endblock %}